name: ci
on: push
jobs:
  test:
    runs-on: ubuntu-24.04
    permissions:
      # allow the release step to comment on
      # issues, pull requests, and write to the repo
      contents: write
      issues: write
      pull-requests: write
      # Required for OIDC to let NPM registry know
      # that this workflow is trusted
      id-token: write
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v6

      - name: Use the right Node version 🧑‍🦲
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc

      - name: Run tests 🧪
        # https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v6
        with:
          # check types
          build: npm run lint

      - name: Semantic Release 🚀
        if: github.ref == 'refs/heads/main'
        uses: cycjimmy/semantic-release-action@v6
        with:
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
