# https://github.com/nielsvaneck/render-md-mermaid
# https://nielsvaneck.com/post/2021-01-31-render-md-mermaid-a-github-action/
name: render-charts

# only re-render Mermaid charts
# if the README file changes on the main branch
# or this workflow file changes
on:
  push:
    branches:
      - main
    paths:
      - README.md
      - .github/workflows/render-charts.yml

jobs:
  render-md-mermaid:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Render images for every Mermaid diagram in all Markdown files (*.md) in the repo
        uses: nielsvaneck/render-md-mermaid@v2

      - run: git status

      - name: Commit rendered png and svg files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: '*[.svg,.png]'
          branch: main
          commit_message: automatically rendered mermaid diagrams
